version: 0.2

phases:
install:
  runtime-versions:
    java: openjdk8
  build:
    commands:
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'target/mservices-1.0.0-SNAPSHOT.jar'
            
